### PR TITLE
LPS-73914 Use same groupId as vocabulary to get categories

### PR DESCRIPTION
**Pull request by JavierMoral**
Hi @Robert-Frampton 
I'm sending this to you because you reviewed https://github.com/Robert-Frampton/liferay-portal/pull/405
A regression in my code has been found in [here](https://issues.liferay.com/browse/LRQA-34717?focusedCommentId=1103188&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1103188) so that child sites cannot see categories of parent sites. In this code, I use vocabulary's groupId instead of ThemeDisplay.scopeGroupId to fix this use case.

Thanks!

### CODE REVIEW

**Comment by JavierMoral** [comment]
Same error https://github.com/brianchandotcom/liferay-portal/pull/51350

**Comment by JavierMoral** [comment]
ci:retest

**Comment by JavierMoral** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51376. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
