### PR TITLE
LPS-53908 This code was removed by error in LPS-52018

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @Robert-Frampton 

As part of https://issues.liferay.com/browse/LPS-52018 you guys removed the code that handles the pagination in comments.

I have included it back in this pull.

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @mjbradford89 @natecavanaugh

**Comment by Robert-Frampton** [comment]
Hey @sergiogonzalez 

Sorry about that, I think it was removed in a bad rebase. I'll get to this now. Thanks!

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3137. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
