### PR TITLE
LPS-72118 Reviewed with the required changes (Rebased)

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:retest

**Comment by dacousalr** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Hey @dacousalr 

This has a rebase conflict with master, can you rebase and resend?

While you're at it do you mind changing the replace token from `{path-context}` to `{contextPath}`?

**Comment by dacousalr** [comment]
Hi @Robert-Frampton,

Yes and yes. #387

Best Regards

**Pull request closed without merging**
