### PR TITLE
LRQA-33716 | master

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
Total Test Failures: 12 (4%)
https://testray.liferay.com/home/-/testray/case_results?filterStatuses=4%2C3%2C1%2C7%2C0&testrayRunId=75326127

May need to disable a few more tests due to known issues on master.

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/836. [See changes here.](https://github.com/Robert-Frampton/liferay-portal/compare/bc41402~6...bc41402) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
