### PR TITLE
[Technical Support] LPS-71856 | master

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @NolanChan

Hey @Robert-Frampton, this is an update for https://issues.liferay.com/browse/LPS-71856.

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/blzaugg/liferay-portal/pull/178. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Hey @dustinryerson and @NolanChan,

I went ahead and forwarded this to @blzaugg since he's run into a similar issue before and is familiar with CKEditor.

**Comment by dustinryerson** [comment]
Sounds good, thanks for the heads up!

**Pull request closed without merging**
