### PR TITLE
[Technical Support] LPS-70366

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @NolanChan

Hey @Robert-Frampton,

Here's an update for https://issues.liferay.com/browse/LPS-70366.

For this fix, I think was we're looking for is the following:
1. Only one password expiration warning notification shows on the page.
2. When the user closes the notification, the notification stays closed for the whole session, even when a use navigates away from the portal without logging out and then navigates back.
3. The notification should reappear when a user logs out and logs back in.

From Nolan:

> The problems that I'm trying to address in this PR are twofold:
> 
> 1. Notice.js was formatting itself really badly in DXP, and given that it's deprecated I opted to move this code over to Notification.js
> 
> 2. Brian and Tsubasa are concerned that the repetitive nature of the password notifications will be extremely annoying, to which I agree. I looked to see if session.js could be of some use, but the functionality wasn't helpful once I understood what it was doing. I settled on using the browser's session to track whether the user has seen the notification, which mimics a lenient number of times for this notification to be shown to the customer. I'm open to brainstorming to figuring out a better way.

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Hey @dustinryerson @NolanChan 

Are we concerned at all with the fact that this alert will behave differently than similar alerts within Portal? I'm a little worried that giving it slightly different behavior than other notifications will cause confusion.

@jonmak08 what are your thoughts?

**Comment by jonmak08** [comment]
Hey guys,

So I am a little hesitant about this fix because say a user has a shared account like an admin account.  If one user logs in and dismisses the notification, when the next user logs in, they will not see this notification.  I agree that the notification popping up on every page is an annoyance, but at the same time it is a reminder for the user to resolve the issues before proceeding.

Another thing about this fix is that by adding a session for this specific notice, do we add it to every notice? add it to only specific ones?  what determines whether we add a session for the notice or not?

I would say like @Robert-Frampton mentioned, the alerts _should_ function similarly.

If you wanted to achieve this functionality, I would say it would make the most sense to add a portal.property where the system admin can explicitly turn on this feature to stop the popup notifications from appearing and knowingly understand the affects it may cause.

Let me know your thoughts.  Thanks guys!

**Comment by NolanChan** [comment]
Hi @jonmak08 and @Robert-Frampton ,

Thanks for looking over the fix. This issue seems to be navigating a grey area within notifications. From my understanding, notifications generally pop up after successful or unsuccessful submissions. However, other JS modules, like Session.js, utilize notifications to display their content as well. It seems like alerts are used as a multi-tool for displaying content in general, and that any sort of user-control over notifications will result in another JS module (which I'm unsure of is being a feature request).

Utilizing the session seems to fit into this interesting sweet spot of how often a password reminder should show up, but I admit that it does look hacky and it does not offer the user any control over how often it should show up. There appears to be no hard and fast rule about when or not to utilize the session, but this specific scenario seems to make sense to me.

Ultimately, I tend to agree with CS that incessant notifications feels unprofessional when talking about a password reminder. However being in TS, I'm unsure as how much of a feature I am allowed to write. Utilizing the session seems to be a compromise given how much I can do.

I'm open to collaborating on another solution or creating a new JS module with control over time and quantity, but as of now I may need some further help if this session solution is not allowed.

Thanks,
Nolan

**Comment by jonmak08** [comment]
Hey @NolanChan and @dustinryerson,

I just spoke with @natecavanaugh to pick his brain about how to best achieve this functionality.  We were saying that we should extend the JS and the Java to allow a persistMessage attribute where the user could pass in ```true``` or ```false``` to control this functionality.  We can have the attribute default to ```true``` so it is backwards compatible, but this would allow you to add this feature just for the password message for now.

Can you implement this feature send us a new pull request?

Please let me know if you have any questions. Thanks!

**Pull request closed without merging**
