### PR TITLE
[Technical Support] LPS-69202

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @rodrigopaulino

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Hey guys,

I think there may be a simpler approach to address this that won't require adding a new attribute. Let's try adding values for `up` and `down` to the horizontal overlay maps. That way we can just target instances where the direction is set to `down`.

```javascript
var MAP_ALIGN_HORIZONTAL_OVERLAY = {
	down: STR_LEFT,
	left: STR_RIGHT,
	right: STR_LEFT,
	up: STR_LEFT
};

var MAP_ALIGN_HORIZONTAL_OVERLAY_RTL = {
	down: STR_RIGHT,
	left: STR_LEFT,
	right: STR_RIGHT,
	up: STR_RIGHT
};
```

We just need to make sure we're not breaking other instances of the taglib where direction is set to `down`. Can you give this a shot? Let me know if you have any other questions,

**Comment by rodrigopaulino** [comment]
Hey, @Robert-Frampton, thanks for taking a look into this.

I see that your suggestion is much less expensive and might fix the whole direction `down` problem all over Liferay Portal. But, after doing a quick text search by `liferay-ui:icon-menu`, I could see a bunch of taglibs that use this one with direction `down` and others with a dynamically calculated direction, expanding even more the places where we could find this taglib being used in Liferay. With that said, wouldn't my solution be more versatile since it opens the possibilities for customizing the horizontal position of the overlaid menu according the necessities of the developer and adding a new attribute would impact less on other use cases and reduce to zero the chance of adding a regression bug?

**Comment by Robert-Frampton** [comment]
Hey @rodrigopaulino

Yes it would make the tag more versatile, but it also makes the api/expected behavior confusing. At first glance how would a developer know the difference between `direction` and `horizontalOverlayDirection`? For example, what is the expected behavior if someone passes in a horizontal value to `direction` in combination with this new attribute?

```
<liferay-ui:icon-menu direction="left" horizontalOverlayDirection="right">
```

**Comment by rodrigopaulino** [comment]
I understand that this could confuse some developers but that is why I explained the behavior in those cases in the attribute's description in the `liferay-ui.tld`.

**Comment by Robert-Frampton** [comment]
Hey @rodrigopaulino 

If we are going to add another attribute to the taglib, I'd rather add one that allows for greater customization that can be used in place of the `direction` attribute. For example, one that allows the developer to pass in the exact align points that the js module uses to position.

```
<liferay-ui:icon-menu alignPoints="TL, BL">
```

That way the values are just a one to one match with the position widget values https://yuilibrary.com/yui/docs/api/classes/WidgetPositionAlign.html. Thoughts?

**Comment by rodrigopaulino** [comment]
Hey, @Robert-Frampton.

I agree with that. The only drawbacks I see to replacing an attribute is that it's going to take a little more time to change all the instances using the direction attribute already and the possibility of breaking some place else that wasn't broken in the first place.

**Comment by Robert-Frampton** [comment]
Hey guys,

We need to be really carful adding new attributes to taglibs when addressing a single use case. First we need to check the other use cases in portal where direction is set to `down` and see if they suffer from the same alignment issues. If so the fix is simple and we avoid complicating the source code.

@dustinryerson / @rodrigopaulino, can you guys work together to find a different solution?

**Pull request closed without merging**
