### PR TITLE
LPS-74571 Update Clay to v2.0.0-alpha.9

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-74571

Also fixed some alignment things in Management Bar, Navbar, cleaned up the imports a bit, and fix empty css properties being output (turns out it was the BS3 box-shadow mixin).

### CODE REVIEW

**Comment by jbalsas** [comment]
hey guys! I've added the RTL test to the PRTester [here](https://github.com/jbalsas/liferay-portal/pull/849#issuecomment-332751641).

As you can see the RTLSmoke still fails after this :(

screen shot 2017-09-28 at 15 43 25

@alee8888, can you help us out? what do you see here?

**Comment by jbalsas** [comment]
BTW, I see RTL working just fine on this branch:

screen shot 2017-09-28 at 16 17 19 2

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51843. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
