### PR TITLE
LPS-72336 removed old properties from portal-developer.properties

### PR DESCRIPTION
**Pull request by mwilliams2014**
cc @blzaugg

Hey @Robert-Frampton,

I've removed some old properties from `portal-developer.properties`.  Can you review and push the changes to Bchan? Let me know if I should send this to someone else instead. thx!

Mike

### CODE REVIEW

**Comment by blzaugg** [comment]
@mwilliams2014, who made to original changes to `portal.properties`?

**Comment by mwilliams2014** [comment]
Looks like Bchan and Nate 3 years ago. I imagine the `portal-developer.properties` file was copied straight over and just not updated.

**Comment by blzaugg** [comment]
Sorry, who made the original removal of `freemarker.engine.cache.storage` from `portal.properties`?

**Comment by mwilliams2014** [comment]
Looks like a big portion of the freemarker properties were removed in this commit: https://github.com/liferay/liferay-portal/commit/cf89b7467935561da4a2dff6e7ed21f8d3ee018c  Still trying to track down when `freemarker.engine.cache.storage` was removed though.

**Comment by mwilliams2014** [comment]
That property isn't even present in our 6.2 portal.properties though. Did you mean another one?

**Comment by blzaugg** [comment]
Just the ones you are removing.

**Comment by mwilliams2014** [comment]
Velocity ones were removed in this commit: https://github.com/liferay/liferay-portal/commit/4451009b3d70ac91c3e3980fb6c5bed97fdaad30 can't find the freemarker cache one

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48930. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
