### PR TITLE
LRQA-34808 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Rebase newest BS4 https://github.com/vicnate5/liferay-portal/pull/836

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
https://github.com/vicnate5/liferay-portal/pull/840

**Pull request closed without merging**
