### PR TITLE
[Technical Support] LPS-71202

### PR DESCRIPTION
**Pull request by dustinryerson**
https://issues.liferay.com/browse/LPS-71202

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
Hey @Robert-Frampton, I saw the error here: https://github.com/brianchandotcom/liferay-portal/pull/47528#issuecomment-286450752

Looks like the taglib exists in ee-7.0.x (where I had to do all my testing so that I could connect to the customer's database), but not in master. Sorry for the oversight on my part.

**Comment by dustinryerson** [comment]
13402d8 uses the correct taglib - I fully compiled everything including JSPs and it should all work.

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
