### PR TITLE
[Technical Support] LPS-72761

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @zsagia @jbalsas 

Hey @Robert-Frampton, here's an update for https://issues.liferay.com/browse/LPS-72761.

It looks like the CSS changes are taken from https://github.com/liferay/alloy-editor/blob/master/dist/alloy-editor/assets/alloy-editor-atlas.css#L224-L232

### CODE REVIEW

**Comment by zsagia** [comment]
Hi @Robert-Frampton ,

This is just a reminder.

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Hey @zsagia @dustinryerson 

It looks like the file you pulled this from should be included when using alloy editor.

https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/alloyeditor.jsp#L66

Is the file just not being loaded properly? Or do the styles set in `alloy-editor-atlas.css` just get overridden by some styling in Portal?

If we can get this to work without copying the css that would be preferable.

**Comment by lipusz** [comment]
Hi Dustin, Robert,

I just wanted to let you know that Zsaga will be OoO in the next 2 weeks.

@dustinryerson: as you reviewed Zsaga's changes maybe you could answer Robert's question.

Thanks!

@dustinryerson @Robert-Frampton

**Comment by Robert-Frampton** [comment]
Hey @dustinryerson 

I will be out the next two weeks, so if you get anywhere on this issue during that time, go ahead and forward the pr to @jonmak08. Thanks!

**Pull request closed without merging**
