### PR TITLE
LPS-64308 Do not use forEach for NodeLists, it doesn't work on IE

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Hey @carloslancha 

Is the intended purpose of this pr to remove the reset button altogether? I didn't quite get that from the description/comments on the JIRA ticket.

**Comment by carloslancha** [comment]
Hey @Robert-Frampton yes, it's intended, UX decision :)

**Comment by Robert-Frampton** [comment]
Hey @carloslancha I was able to reproduce the issue with the close button.

apr-19-2017 10-37-08

Steps:

1) Open Look and Feel config for welcome portlet
2) Change background color
3) Click `Close` button (do not save changes)
4) Reopen config modal
5) Click `Close` again and assert that it doesn't close the modal

**Comment by carloslancha** [comment]
Oh @Robert-Frampton that happens with any of the configuration modals with cancel button. When you:

- Open any configuration like Look and Feel or Permisions,
- Click cancel
- Open the same configuration again
- Click cancel

That's another issue (we should probably open a ticker for that bug). Please, ignore that for this pr.

Thanks!

**Comment by Robert-Frampton** [comment]
Oh gotcha. Thanks @carloslancha, sorry for the delay.

**Comment by Robert-Frampton** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/48481

**Pull request closed without merging**
