### PR TITLE
LPS-74624

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @gregory-bretall 

https://issues.liferay.com/browse/LPS-74624

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
Hey @dustinryerson @gregory-bretall 

If you happen to focus the input on really small screens, the add button pops up on top of the product menu.

screen shot 2017-09-14 at 12 54 29 pm

I think a lot of users would perceive this as a bug. Can we only set the z-index to `1050` at screen widths where the product menu doesn't overlap the input? For example, I think this is fine...

screen shot 2017-09-14 at 12 57 30 pm

But it looks strange at the smaller resolution to me.

**Comment by gregory-bretall** [comment]
@Robert-Frampton , do you think it would be reasonable to target the z-index change only at the product menu and not at the add button?  If so I can change the location of the css class.  Otherwise if you think it's best to only render the z-index change for smaller resolutions I can make that change too.  Just let me know what you think.

**Comment by Robert-Frampton** [comment]
I think we should leave the z-index of the product menu alone, we don't want to break any other areas.

My suggestion was actually to only set the z-index to `1050` of the AlloyEditor elements on screen sizes >= `768px`. That way it will still look like the second screenshot above, but on smaller screens we won't see the button overlap seen in the first screen shot.

**Comment by Robert-Frampton** [comment]
Hey @gregory-bretall. Did you mean target the alloy editor toolbar but not the add button? I think that solution should work as well.

**Comment by gregory-bretall** [comment]
Yes, sorry I meant the Alloy toolbar.  Just to confirm, you think that it would be ok to always keep the toolbar menu's z-index at 1050 or do you still think it should be only at that x-index for screen sizes larger than 768px?

**Comment by Robert-Frampton** [comment]
Hey @gregory-bretall 

I'd like to go with only setting the z-index to `1050` on screen sizes >= `768px`. This means on small screen sizes it's still going to look like this...

screen shot 2017-09-14 at 2 35 12 pm

This is because at that screen width the input itself is being overlapped by the product menu. In that scenario it doesn't make sense for the editor tools to overlap the product menu when the editor ins't even fully visible.

I'm not sure if this _exactly_ addresses what the client was reporting, but I think we can push back a little on it. @dustinryerson what do you think?

**Comment by gregory-bretall** [comment]
Ok, I resent a pull to Dustin with the changes, found here https://github.com/dustinryerson/liferay-portal/pull/161 so you can close this PR.

**Pull request closed without merging**
