### PR TITLE
[Technical Support] LPS-70748

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @gregory-bretall 

https://issues.liferay.com/browse/LPS-70748

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Hey @dustinryerson / @gregory-bretall 

What do you think about making the container of the modal scrollable? That way we account for clients that might complain about not being able to see elements on the bottom either, since this fix only accounts for elements on top.

**Comment by dustinryerson** [comment]
Sounds like a good idea to me. Greg should be able to respond tomorrow I think.

**Comment by gregory-bretall** [comment]
That seems like a reasonable fix to me, I think we can go ahead with it.  Thanks!

**Comment by Robert-Frampton** [comment]
Cool, I'm going to go ahead and close this one out for now. Thanks, guys

**Comment by gregory-bretall** [comment]
Hey @Robert-Frampton  just to be clear, do you want me to work on the proposed fix or will you?

**Comment by Robert-Frampton** [comment]
Hey @gregory-bretall if you could that would be great.

**Comment by gregory-bretall** [comment]
Ok, I'll get to work on that and send you a new PR when I'm done with it.  Thanks!

**Pull request closed without merging**
