### PR TITLE
LPS-73502

### PR DESCRIPTION
**Pull request by dustinryerson**
Hey @Robert-Frampton,

Here's an update for https://issues.liferay.com/browse/LPS-73502.

Please let me know if you have any questions.

Thanks!

/cc @omarzzn3 @dsanz @zsigmondrab

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:stop

**Comment by dustinryerson** [comment]
ci:restart

**Comment by dustinryerson** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
Hey @dustinryerson 

From what I'm seeing, this is only an issue with `textarea` elements, meaning this change will unnecessarily remove the placeholder on `input` elements as well. Can we modify it so that we are only removing the placeholder for textareas?

Also it looks like it's broken in IE 10 as well, let's go ahead and address it for both.

**Comment by dustinryerson** [comment]
@Robert-Frampton thanks for your input! I've updated the fix (https://github.com/Robert-Frampton/liferay-portal/pull/392/commits/38e4672aa9528d7f42a9a378d66477d53013d517) to disable placeholders in IE10, and I've limited the fix to just `text` and `textarea` input field types. During my testing I noticed the issue occurred with both types.

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Hey @dustinryerson. When you tested it with `type="text"`, was it rendering a `textarea` or an `input`? I just tried it and it seems ok to me, but maybe my test case isn't the same as yours.

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50185. [See changes here.](https://github.com/Robert-Frampton/liferay-portal/compare/43cb74d~1...43cb74d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Hey @dustinryerson 

Just a heads up that I removed the check for `type="text"` because I wasn't able to reproduce it. If you think it's still necessary please let me know. Thanks,

**Pull request closed without merging**
