### PR TITLE
LPS-75086

### PR DESCRIPTION
**Pull request by dustinryerson**
https://issues.liferay.com/browse/LPS-75086

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Hey @gregory-bretall 

Did you try using the [entities_greek](https://docs.ckeditor.com/ckeditor4/docs/#!/api/CKEDITOR.config-cfg-entities_greek) config option by any chance?

My only concern is that setting `entities` to false might have unintended side effects.

**Comment by gregory-bretall** [comment]
That would also be a workable solution, I only set entities in general because that is the property we have set for regular CKEditor (https://github.com/gregory-bretall/liferay-portal/blob/master/modules/apps/foundation/frontend-editor/frontend-editor-ckeditor-web/src/main/java/com/liferay/frontend/editor/ckeditor/web/internal/editor/configuration/CKEditorConfigContributor.java#L74) and I assumed we'd want the same behavior. Looking back on it that wasn't a very founded assumption though so if you think it's best to just play it safe, feel free to change it to entities_greek or I can do that and resend you the PR with that change.

**Comment by Robert-Frampton** [comment]
Gotcha, makes sense. If configure CKEditor that way then it only makes sense to keep things consistent. Thanks,

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52001. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52003. [See changes here.](https://github.com/Robert-Frampton/liferay-portal/compare/7bda04b~1...7bda04b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
