### PR TITLE
LPS-70758 Navigation and Search portlet are missing when impersonating a newly created user

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @Robert-Frampton, I'm forwarding this one since I won't have time to go over this any time soon...

Could you please take a look? We've tried several approaches here, and in the end (even though we don't like this at all), this seems to be the easiest and actually more consistent one.

@izaera has more context in case you have any questions.

Thanks!!

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Hey @jbalsas @izaera 

Is this issue also reproducible on custom themes? If so this fix isn't going to resolve the issue for theme devs.

**Comment by Robert-Frampton** [comment]
Hey guys,

If we apply these same changes to the base theme's `portal_normal.ftl`, it will cause regressions for theme developers if they deploy against an older fix pack that doesn't have the changes made to `FTL_liferay.ftl`.

If we don't plan to make these changes to the base theme, then this PR is fine and won't cause regressions. So what's the plan with this approach? Are we intending to make similar changes to the base theme templates?

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, we've been doing a lot of back and forth on this one... the original request was https://github.com/marcoscv-work/liferay-portal/pull/61 which simply changed things in the themes. 

After all this time and effort, and considering we'll at sooner or later have to rewrite the themes anyway, I'm leaning towards simply accept that one and move forward.

What do you think?

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Hey guys,

After taking a closer look at these changes, and the changes from https://github.com/marcoscv-work/liferay-portal/pull/61, I think a hybrid approach will be the safest. That means go ahead and make the changes to the macros, but also do the check in the individual themes as well. That way the themes will still behave correctly on older releases of Portal, and it will allow us to remove those checks from future 7.1 themes.

Thoughts?

**Comment by Robert-Frampton** [comment]
Already mentioned this here https://github.com/jbalsas/liferay-portal/pull/725, but it looks like this was merged already? 

https://github.com/liferay/liferay-portal/commit/999bc9b68395f12df7ee44820c51cfdabdeb3203

**Pull request closed without merging**
