### PR TITLE
LPS-58654 - Fake Gradle cache

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Related to: https://github.com/Robert-Frampton/generator-liferay-theme/pull/2

/cc @natecavanaugh

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3967. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/natecavanaugh/liferay-portal/pull/3968. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
