### PR TITLE
LPS-73914

### PR DESCRIPTION
**Pull request by dustinryerson**
Hey @Robert-Frampton,

This is an update for https://issues.liferay.com/browse/LPS-73914.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
@dustinryerson 

Did the tests pass when these changes were sent to you? Looks like it failed twice on the same test.

**Comment by dustinryerson** [comment]
@Robert-Frampton I think it might be a flakey test, it passed on my repo: https://github.com/dustinryerson/liferay-portal/pull/155#issuecomment-321763367

**Comment by dustinryerson** [comment]
@Robert-Frampton I'm going to try running the tests one more time. I'm also going to rerun the tests on my repo to see if I get similar results.

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
Looks like similar tests are failing on other pull requests and repos:
1. https://github.com/brianchandotcom/liferay-portal/pull/50964#issuecomment-322725722
2. https://github.com/brianchandotcom/liferay-portal/pull/50958#issuecomment-322650896
3. https://github.com/hhuijser/liferay-portal/pull/2968#issuecomment-322755728

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dustinryerson** [comment]
I reran the tests on my repo earlier today and they have passed: https://github.com/dustinryerson/liferay-portal/pull/156#issuecomment-323227517

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51037. [See changes here.](https://github.com/Robert-Frampton/liferay-portal/compare/96b535a~2...96b535a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
