### PR TITLE
LPS-61596 - Extract liferay-look-and-feel.xml to individual theme bundles

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Rob,

Attached are the changes to migrate the liferay-look-and-feel.xml to our theme modules.

We could maybe have Chema or Ray review the backend changes once you and Nate approve the xml stuff.   

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Hey @mjbradford89 

I ran an ant all on this pull and I'm getting some errors on startup.

https://gist.github.com/Robert-Frampton/8b38f8fe8b2c6adb1fd7

Do I need to clean anything before building?

**Comment by mjbradford89** [comment]
Hey @Robert-Frampton,

Hmm, running ant all should be enough.  One thing you could possibly try is delete the contents  in `bundles/osgi/state` in your server and restart it.

**Comment by mjbradford89** [comment]
Let me know if that doesn't work and I'll try and reproduce it

**Comment by Robert-Frampton** [comment]
Alrighty, I deleted the contents of the state directory and ran a git clean
-d -f in case something left over from another branch was blowing stuff up.
I'll let you know what happens.

**Comment by mjbradford89** [comment]
cool, thanks!

**Comment by Robert-Frampton** [comment]
Looks like I'm getting the same stack trace as before.

**Comment by mjbradford89** [comment]
Ah okay, that's so weird.  I had seen that same error yesterday but it went away after running ant all.  there must be a bug somewhere.  I'll look into it and let you know if I figure it out.  Thanks Rob

**Comment by Robert-Frampton** [comment]
Ok, so I cleared out my data, work, and temp directories and restarted. I
got this error still

18:21:22,266 WARN  [localhost-startStop-1][ThemeLocalServiceImpl:250] No
theme found for specified theme id classic. Returning the default theme.

But the Portal actually started up ok, and once it was running it no longer
threw that error, and classic theme displayed properly. I'm going to
restart it once more to see if that error shows up again, though I'm
thinking either way we should make sure that error doesn't get thrown on
first start up.

On Tue, Jan 12, 2016 at 10:21 AM, Michael Bradford <notifications@github.com

**Comment by mjbradford89** [comment]
ah okay, interesting.  I'm running ant all now to see if I get the same.

**Comment by mjbradford89** [comment]
I got that same NPE error you got at first.  The code I put in to ensure the themes bundles are starting before we read the xmls must not be working the way I expected.  I'll let you know once I've got this figured out.  Sorry for the time wasting :disappointed:

**Comment by Robert-Frampton** [comment]
No worries at all! I tried restarting my tomcat, and the errors didn't show
up that time. So it seems like it only happens on initialization.

On Tue, Jan 12, 2016 at 10:39 AM, Michael Bradford <notifications@github.com

**Comment by mjbradford89** [comment]
Hey @Robert-Frampton,  This should be ready now.  I had to change the order of which some things are initialized when the portal starts, hopefully I didn't break anything else :sweat_smile: .  Please let me know if there are any issues,  Thanks!

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Hey @mjbradford89 

Looks good to me. Since I'm not super familiar with the changes to MainServlet.java, you wanna send this straight to Ray? I don't have any changes to make to the liferay-look-and-feel.xml files.

**Comment by mjbradford89** [comment]
Thanks @Robert-Frampton!  Sure, I'll send it along.

**Pull request closed without merging**
