### PR TITLE
LPS-70797 - Move layouttpl plugins to DXP

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @Robert-Frampton!

We want to move all the column layouts from https://github.com/liferay/liferay-plugins/tree/master/layouttpl to a single app in master that is meant to be released to the marketplace. We've grouped all of them in a single app for easier management.

b7efd2aa-f854-11e6-83c9-76c71c0f78c9

@marcoscv-work tried using the `node-tasks` to generate the war, but maybe for this we can make it even easier using the default gradle tasks. Could you work with @ithildir on this?

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
b7efd2aa-f854-11e6-83c9-76c71c0f78c9

**Comment by Robert-Frampton** [comment]
Hey @jbalsas 

I was going to take a look at this today but noticed you closed it. What's the status on this?

**Comment by jbalsas** [comment]
oops! I was doing spring branch cleaning and must've deleted it 😣

Could you fetch it from marcos?

**Comment by Robert-Frampton** [comment]
Yep, no problem.

**Pull request closed without merging**
