### PR TITLE
LPS-72991

### PR DESCRIPTION
**Pull request by dustinryerson**
Hey @Robert-Frampton,

Here's an additional commit to fix a minor issue with https://issues.liferay.com/browse/LPS-72991.

Please let me know if you have any questions.

Thanks!

From Daniel:

> I detected a minor glitch if there is more than one input-localized. The fix is pretty trivial.

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50292. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
