### PR TITLE
LPS-70791

### PR DESCRIPTION
**Pull request by dustinryerson**
Hey @Robert-Frampton,

Here's an update for https://issues.liferay.com/browse/LPS-70791. There's some discussion about ticket descriptions and context here: https://github.com/dustinryerson/liferay-portal/pull/120#issuecomment-314363778

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50313. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
