### PR TITLE
LPS-75058

### PR DESCRIPTION
**Pull request by dustinryerson**
Hey @Robert-Frampton,

Here's an update for https://issues.liferay.com/browse/LPS-75058.

Thanks!

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Pull request submitted to https://github.com/izaera/liferay-portal/pull/22. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
ci:stop

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
@dustinryerson Please add the **[TS]** designation to the subject as it's customer related.

**Comment by lipusz** [comment]
ci:reopen

**Pull request closed without merging**
